polls/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('pollsapp.urls'))
]

pollsapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'pollsapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserRegistrationView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'add/$', views.PollCreate.as_view(), name='poll-add'),
    url(r'^(?P<poll_id>[0-9]+)/vote', views.vote, name='vote'),
    url(r'^login/$', views.UserLoginView.as_view(), name='login')
]

pollsapp/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Poll(models.Model):
    def __str__(self):
        return self.poll_title

    def get_absolute_url(self):
        return reverse('pollsapp:detail', kwargs={'pk': self.pk})

    poll_title = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

pollsapp/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(widget=forms.TextInput)

    class Meta:
        fields = ['username', 'password']

pollsapp/views.py
from .models import Poll, Choice
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, LoginForm

# def index(request):
#     all_polls = Poll.objects.all()
#     context = {
#         'all_polls': all_polls,
#     }
#     return render(request, 'pollsapp/index.html', context)
#
#
# def detail(request, poll_id):
#     poll = get_object_or_404(Poll, id=poll_id)
#     return render(request, 'pollsapp/detail.html', {'poll': poll})


def vote(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    try:
        selected_choice = poll.choice_set.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'pollsapp/detail.html', {'poll': poll, 'error_message': 'Please select an answear'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return render(request, 'pollsapp/detail.html', {'poll': poll})


class IndexView(generic.ListView):
    template_name = 'pollsapp/index.html'
    context_object_name = 'all_polls'

    def get_queryset(self):
        return Poll.objects.all()


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'pollsapp/detail.html'


class PollCreate(CreateView):
    model = Poll
    fields = ['poll_title', 'pub_date']


class PollUpdate(UpdateView):
    model = Poll
    fields = ['poll_title', 'pub_date']


class AlbumDelete(DeleteView):
    model = Poll
    success_url = reverse_lazy('pollsapp:index')


class UserRegistrationView(View):
    form_class = UserForm
    template_name = 'pollsapp/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('pollsapp:index')

        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = LoginForm
    template_name = 'pollsapp/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request=request, username=username, password=password)

            if user is None:
                form.add_error(None, 'user/pass combination does not add upp.')
            elif user.is_active:
                login(request, user)
                return redirect('pollsapp:index')

        return render(request, self.template_name, {'form': form})

pollsapp/templates/pollsapp/detail.html
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<h1> {{ poll }} </h1>

<form action="{% url 'pollsapp:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <input type="radio" id="{{ forloop.counter }}" name="choice", value={{ choice.id }} />
        <label for="choice{{ forloop.counter }}">
            {{ choice }}
        </label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

pollsapp/templates/pollsapp/form-template.html
{% if form.errors %}
{% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% for field in form %}
    {{ field.errors }}
    <label>{{ field.label_tag }}</label>
    {{ field }}
{% endfor %}

pollsapp/templates/pollsapp/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'pollsapp/style.css' %}" />

{% if all_polls %}
    <h1>Polls list:</h1>
    <ul>
        {% for poll in all_polls %}
        <li><a href="{% url 'pollsapp:detail' poll.id %}">{{ poll.poll_title }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <h2>You don't have any polls</h2>
{% endif %}
<a href="{% url 'pollsapp:poll-add' %}">Create poll</a> <br>
<a href="{% url 'pollsapp:register' %}">Register</a><br>
<a href="{% url 'pollsapp:login' %}">Login</a>

pollsapp/templates/pollsapp/poll_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'pollsapp/form-template.html' %}
    <button type="submit">Sumbit</button>
</form>

pollsapp/templates/pollsapp/registration_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'pollsapp/form-template.html' %}
    <button type="submit">Sumbit</button>
</form>